#! /usr/bin/env bash

PROGRAM=${1};
APP_PATH=${2};

tmux split-window -p 25 -c ${APP_PATH} -t 0;
tmux new-window -c ${APP_PATH} -n "Server" -t 3;
tmux select-window -t 0;
tmux select-pane -t 0;
vim +NERDTree;
